### ISSUE TITLE
[Bug Report][Android] library "libavcodec.so" not found

### ISSUE THREAD

**Issue by MickaelHrndz** [media-kit/media-kit#283] opened 2023-07-13 09:18 UTC
Hello again,

I am trying to use the `ffmpeg_kit_flutter_min_gpl` package alongside `media_kit` on Android. It is working without issues on a physical Android 13 and on an emulated Android 7.1.1. But when running it on a physical Android 7.1.2 (a box called Pendoo X8 mini), I get this error :

```
I/flutter (13617): Invalid argument(s): Failed to load dynamic library 'libavcodec.so': dlopen failed: library "libavcodec.so" not found
I/flutter (13617): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
I/flutter (13617): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
I/flutter (13617): #2      AndroidHelper.ensureInitialized (package:media_kit/src/utils/android_helper.dart:23:43)
I/flutter (13617): #3      libmpvEnsureInitialized (package:media_kit/src/player/libmpv/player/real.dart:40:17)
I/flutter (13617): #4      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:39:7)       
I/flutter (13617): #5      main (package:vctv_flutter/main.dart:12:12)
I/flutter (13617): #6      _runMain.<anonymous closure> (dart:ui/hooks.dart:131:23)
I/flutter (13617): #7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
I/flutter (13617): #8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
E/flutter (13617): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv.so. Please ensure it's presence in the APK.
E/flutter (13617): #0      NativeLibrary.ensureInitialized (package:media_kit/src/player/libmpv/core/native_library.dart:63:9)
E/flutter (13617): #1      libmpvEnsureInitialized (package:media_kit/src/player/libmpv/player/real.dart:41:17)
E/flutter (13617): #2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:39:7)       
E/flutter (13617): #3      main (package:vctv_flutter/main.dart:12:12)
E/flutter (13617): #4      _runMain.<anonymous closure> (dart:ui/hooks.dart:131:23)
E/flutter (13617): #5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
E/flutter (13617): #6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

I'm aware of #241, here's my dependencies :
```
  media_kit: ^1.0.2
  media_kit_video: ^1.0.2
  media_kit_native_event_loop: ^1.0.6  
  media_kit_libs_android_video: ^1.1.1
  ffmpeg_kit_flutter_min_gpl: ^5.1.0
```

As described in #159, I tried adding the `packagingOptions` part to the `build.gradle` but it didn't solve the issue.

Any clue on how to solve this ? Thank you.

**Comment by MickaelHrndz** [comment] 2023-07-13 13:34
I just tried with the following deps, still the same error :
```
  media_kit: ^1.0.2
  media_kit_video: ^1.0.2
  media_kit_native_event_loop: ^1.0.6  
  media_kit_libs_android_video: ^1.1.1
  media_kit_libs_ios_video: ^1.0.4
  media_kit_libs_macos_video: ^1.0.5
  media_kit_libs_windows_video: ^1.0.2    
  media_kit_libs_linux: ^1.0.2
  ffmpeg_kit_flutter_full_gpl: ^5.1.0
```

**Comment by alexmercerind** [comment] 2023-07-13 21:13
Marking "in triage" for further investigation. We'll need further details.

**Comment by alexmercerind** [comment] 2023-07-18 20:06
Hi!

I just noticed your edit. I apologies for the delays; we're working really hard on Android side of things.

I just wanted to ask does ffmpeg_kit_flutter_min_gpl itself work on that machine (after removing media_kit)?
In our Android build steps, we ignore our version of FFmpeg if existing FFmpeg is located.

**Comment by MickaelHrndz** [comment] 2023-07-19 07:52
It does work, yes.

**Comment by alexmercerind** [comment] 2023-07-19 08:09
And media_kit also works independently?

**Comment by MickaelHrndz** [comment] 2023-07-20 08:06
Yes. One other difference is that the box has root access.

**Comment by alexmercerind** [comment] 2023-07-20 10:47
I repeat the question again for confirmation, does media_kit itself work on this device without FFmpeg?

**Comment by alexmercerind** [comment] 2023-07-20 10:53
A number of improvements have been made in regards to performance, stability & size. I'd like to fix this issue before our next stable release.

You may get closely in touch to provide necessary feedback at our Discord:
https://discord.gg/z75Z9NNWJk

**Comment by MickaelHrndz** [comment] 2023-07-24 11:59
For the record, the issue comes from the armeabi-v7a architecture for the `ffmpeg_kit` packages. The files for it in the apk have a "_neon" suffix that makes `media_kit` not able to find and use them, if I understood correctly.

![image](https://github.com/alexmercerind/media_kit/assets/4682969/498b7144-4eab-4dd8-bf63-eef5ccb158d0)

A temporary fix is to use a local copy of the `media_kit_libs_android_video` package and edit this line:
in [android/build.gradle](https://github.com/alexmercerind/media_kit/blob/308bd2694d3c394730fabd18a7e2d552e44021e3/libs/android/media_kit_libs_android_video/android/build.gradle#L210) :
```diff
- destNoFFmpegARMEABI
+ destDefaultARMEABI
```

**Comment by alexmercerind** [comment] 2023-07-26 23:20
I'm fixing the issue completely. Statically linking libav* with libmpv, expect update tomorrow.

**Comment by alexmercerind** [comment] 2023-07-29 13:23
The issue is resolved in the latest update.

Please [refer to the "Installation" section](https://github.com/media-kit/media-kit#installation).

**Closed by alexmercerind** 2023-07-29 13:23 UTC
Labels: platform: android, re-evaluate in future

**Comment by codeswot** [comment] 2024-02-13 15:29
running on an android TV Emulator with the arm64 arch I got the error bellow
`Exception: Cannot find libmpv.so. Please ensure it's presence in the APK.`

the weird this is I also get this error
`media_kit: ERROR: MediaKit.ensureInitialized
I/flutter ( 9680): This indicates that one or more required dependencies could not be located.
I/flutter ( 9680): 
I/flutter ( 9680): Refer to "Installation" section of the README for further details`

while I am sure I installed the packages as stated 

  media_kit: ^1.1.10                            
  media_kit_video: ^1.2.4                       
  media_kit_libs_video: ^1.0.4

**Comment by zezo357** [comment] 2024-02-13 17:59
> running on an android TV Emulator with the arm64 arch I got the error bellow `Exception: Cannot find libmpv.so. Please ensure it's presence in the APK.`
> 
> the weird this is I also get this error `media_kit: ERROR: MediaKit.ensureInitialized I/flutter ( 9680): This indicates that one or more required dependencies could not be located. I/flutter ( 9680): I/flutter ( 9680): Refer to "Installation" section of the README for further details`
> 
> while I am sure I installed the packages as stated
> 
> media_kit: ^1.1.10 media_kit_video: ^1.2.4 media_kit_libs_video: ^1.0.4

did you close the app and recompile it? most probably thats the issue

**Comment by codeswot** [comment] 2024-02-13 18:09
> > running on an android TV Emulator with the arm64 arch I got the error bellow `Exception: Cannot find libmpv.so. Please ensure it's presence in the APK.`
> > the weird this is I also get this error `media_kit: ERROR: MediaKit.ensureInitialized I/flutter ( 9680): This indicates that one or more required dependencies could not be located. I/flutter ( 9680): I/flutter ( 9680): Refer to "Installation" section of the README for further details`
> > while I am sure I installed the packages as stated
> > media_kit: ^1.1.10 media_kit_video: ^1.2.4 media_kit_libs_video: ^1.0.4
> 
> did you close the app and recompile it? most probably thats the issue

I did, I even installed the app and tried again.

**Comment by zezo357** [comment] 2024-02-13 18:21
> > > running on an android TV Emulator with the arm64 arch I got the error bellow `Exception: Cannot find libmpv.so. Please ensure it's presence in the APK.`
> > > the weird this is I also get this error `media_kit: ERROR: MediaKit.ensureInitialized I/flutter ( 9680): This indicates that one or more required dependencies could not be located. I/flutter ( 9680): I/flutter ( 9680): Refer to "Installation" section of the README for further details`
> > > while I am sure I installed the packages as stated
> > > media_kit: ^1.1.10 media_kit_video: ^1.2.4 media_kit_libs_video: ^1.0.4
> > 
> > did you close the app and recompile it? most probably thats the issue
> 
> I did, I even installed the app and tried again.

Can you open a new issue explaining how to reproduce the same issue?

**Comment by codeswot** [comment] 2024-02-13 19:16
Sure thing
