### ISSUE TITLE
media-kit won't work without DCL 

### ISSUE THREAD

**Issue by randomwithnoname** [media-kit/media-kit#1015] opened 2024-10-31 18:27 UTC
Test app (or any app using media-kit such as Aves, where this was originally [discovered](https://github.com/deckerst/aves/issues/1271)) will not work without DCL, therefore intentionally is crashed by the OS.

**Comment by alexmercerind** [comment] 2024-10-31 18:33
Thanks for the report... Users of GrapheneOS reported something similar some time ago... it came out be an actual bug from my end. What happens if you use mpv for Android on your device?
- https://github.com/mpv-android/mpv-android
- https://play.google.com/store/apps/details?id=is.xyz.mpv

**Comment by alexmercerind** [comment] 2024-10-31 19:03
Yeah! I recall... Thanks for the detail. Does mpv for Android also cause same issue?

**Comment by randomwithnoname** [comment] 2024-10-31 19:08
MPV works fine

**Comment by cillyvms** [comment] 2024-11-01 21:18
I can reproduce this issue on the test app from a recent actions run, however not the one linked in the readme. It seems like this is a regression introduced in the last year. I'll try to pinpoint the change causing this.

**Comment by cillyvms** [comment] 2024-11-02 04:51
Turns out the root cause of this issue isn't even in media-kit, but in the Dart VM.

As for media-kit the issue first appears in commit c3cde1f8c30e5f32187c10bba7705e8979b7e0f8, where migration to Dart's `NativeCallable.listener` was completed. There is nothing wrong about media-kit code, just the use of this problematic API.

The core of this issue is that Dart's implementation of callable listeners relies on duplicating memory pages containing code loaded from a file during runtime. On Linux there isn't a syscall for this, so they just copy the code and mark the pages as executable, which is what DCL is blocking. On iOS this is blocked as a baseline, so they've implemented a special case for this with an iOS kernel specific syscall.
https://github.com/dart-lang/sdk/blob/5b6e6865b03f808d9e1e74e4638c997650294839/runtime/vm/virtual_memory.cc#L48-L87

The code isn't expecting errors when marking memory as executable and crashes the whole app when it fails.
https://github.com/dart-lang/sdk/blob/5b6e6865b03f808d9e1e74e4638c997650294839/runtime/vm/virtual_memory_posix.cc#L420-L429

The same restriction seems to apply to Fuchsia, where they are currently skipping the copying process and just using the single memory page as-is.
https://github.com/dart-lang/sdk/blob/5b6e6865b03f808d9e1e74e4638c997650294839/runtime/vm/ffi_callback_metadata.cc#L41-L54

While this could be fixed in the short term by bringing back the isolate based event loop in media-kit as a fallback, this needs to be addressed in the Dart codebase, since we can't expect everyone using this API to implement special casing for restricted DCL.

**Comment by alexmercerind** [comment] 2024-11-02 07:32
> While this could be fixed in the short term by bringing back the isolate based event loop in media-kit as a fallback, this needs to be addressed in the Dart codebase, since we can't expect everyone using this API to implement special casing for restricted DCL.

Sounds good to me. We can expose some bool/enum in the `PlayerConfiguration` to let the dependents choose the preferred event loop mechanism:
- `NativePlayerEventLoop.nativeCallable`
- `NativePlayerEventLoop.isolate`

The main problem with isolate based event loop was that it could only allow a fixed number of concurrent instances (caused Dart VM to freeze after that limit). I think Aves will never reach this limit, ~ 8 IIRC. On the other hand, `media_kit_native_event_loop` was just extremely complex solution to this problem at that time.

Thanks a lot for taking your time in this @cillyvms. I am really impressed, you seem to have a great background in all this. You analysed not only Dart VM, but the details/history of media-kit as well. Great work!

**Comment by cillyvms** [comment] 2024-11-02 22:46
Thank you for the kind words!
I could try to get the isolate based event loop back in, playing some videos should be better than playing none.

However, since the issues with native callable are really dependent on the device configuration, I think it'd be better to just include a small check in media-kit and automatically fallback to isolates when the device is blocking new executable memory. No need to bother app developers with figuring out which loop is required individually.

Let me know if that approach would work for you.

**Comment by alexmercerind** [comment] 2024-11-03 12:48
> I think it'd be better to just include a small check in media-kit and automatically fallback to isolates when the device is blocking new executable memory. No need to bother app developers with figuring out which loop is required individually.

Sure! That will be good.

I am not sure if its feasible to have such a check... the process seems to crash right away, based on what you people are telling me. If you are aware of any approach, let us know / make a pull-request... it may be a good idea to "query" the check once & keep the result cached (so that subsequent instances can be created without that additional code path).

**Comment by cillyvms** [comment] 2024-11-04 17:53
> it may be a good idea to "query" the check once & keep the result cached
Great, that's what I had in mind.

> I am not sure if its feasible to have such a check... the process seems to crash right away
The crash is caused by Dart not implementing different error handling for failures in `mprotect()`, it just aborts.
It should be as simple as getting the `mmap` function from libc and trying to make an executable mapping, it returns a permission denial and invalid pointer if blocked. I'll open a PR soon.

**Closed** 2024-11-11 07:19 UTC
Labels: bug, backend: native
