### ISSUE TITLE
Setting command line is not supported

### ISSUE THREAD

**Issue by soulcure** [media-kit/media-kit#487] opened 2023-09-21 08:13 UTC
Setting command line is not supported, such as setting the no-delay parameter for live streaming --zero-latency=yes

**Comment by 23doors** [comment] 2023-09-21 08:18
Duplicate of https://github.com/media-kit/media-kit/issues/373

There is no command line to speak of but setting parameters is already possible. `zero-latency` doesn't seem to be a valid mpv option though.

**Closed by 23doors** 2023-09-21 08:18 UTC
