### ISSUE TITLE
Using  this package with `package:flutter_ffmpeg_kit_*` causes `JSONException` error

### ISSUE THREAD

**Issue by ragasubekti** [media-kit/media-kit#169] opened 2023-04-29 15:59 UTC
Using both `flutter_ffmpeg_kit_*` with `media_kit` causes some trouble with json handling on native side, it throws JSONException.
It only reproducible after adding `media_kit` packages. Changing the ffmpeg_kit to different version such as `min_gpl` as suggested in #159 also didn't work.

Minimal Code to Reproduce:
```
  final ffprobe = await FFprobeKit.getMediaInformation(filePath);
  final mediaInfo = ffprobe.getMediaInformation(); 
```

Logs:
```
I/flutter ( 5772): Loading ffmpeg-kit-flutter.
D/ffmpeg-kit-flutter( 5772): FFmpegKitFlutterPlugin com.arthenica.ffmpegkit.flutter.FFmpegKitFlutterPlugin@192cec5 started listening to events on io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation@1ab98fb.
I/flutter ( 5772): Loaded ffmpeg-kit-flutter-android-video-x86_64-5.1.0-lts.
W/ffmpeg-kit( 5772): Get media information execute failed: -v error -hide_banner -print_format json -show_format -show_streams -show_chapters -i /storage/emulated/0/Download/BigBuckBunny.mp4.org.json.JSONException: End of input at character 0 of 
W/ffmpeg-kit( 5772): 	at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
W/ffmpeg-kit( 5772): 	at org.json.JSONTokener.nextValue(JSONTokener.java:101)
W/ffmpeg-kit( 5772): 	at org.json.JSONObject.<init>(JSONObject.java:165)
W/ffmpeg-kit( 5772): 	at org.json.JSONObject.<init>(JSONObject.java:182)
W/ffmpeg-kit( 5772): 	at com.arthenica.ffmpegkit.MediaInformationJsonParser.fromWithError(MediaInformationJsonParser.java:65)
W/ffmpeg-kit( 5772): 	at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
W/ffmpeg-kit( 5772): 	at org.json.JSONTokener.nextValue(JSONTokener.java:101)
W/ffmpeg-kit( 5772): 	at org.json.JSONObject.<init>(JSONObject.java:165)
W/ffmpeg-kit( 5772): 	at org.json.JSONObject.<init>(JSONObject.java:182)
W/ffmpeg-kit( 5772): 	at com.arthenica.ffmpegkit.FFmpegKitConfig.getMediaInformationExecute(FFmpegKitConfig.java:707)
W/ffmpeg-kit( 5772): 	at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
W/ffmpeg-kit( 5772): 	at org.json.JSONTokener.nextValue(JSONTokener.java:101)
W/ffmpeg-kit( 5772): 	at org.json.JSONObject.<init>(JSONObject.java:165)
W/ffmpeg-kit( 5772): 	at org.json.JSONObject.<init>(JSONObject.java:182)
W/ffmpeg-kit( 5772): 	at com.arthenica.ffmpegkit.flutter.MediaInformationSessionExecuteTask.run(MediaInformationSessionExecuteTask.java:44)
```

Package Version:
```
  # FFMPEG
  ffmpeg_kit_flutter_video: 5.1.0-LTS

  # MEDIA KIT
  media_kit: ^0.0.7
  media_kit_video: ^0.0.9
  media_kit_libs_android_video: ^1.0.3
  ```

**Comment by deckerst** [comment] 2023-06-27 21:54
I stumbled upon the same issue with the current version of `media_kit`.
```
ffmpeg_kit_flutter_full: 5.1.0-LTS

media_kit: 0.0.11
media_kit_video: 0.0.12
media_kit_libs_android_video: 1.0.6
media_kit_native_event_loop: 1.0.5
```

**Comment by alexmercerind** [comment] 2023-07-29 13:27
The issue is resolved in the latest update. Better late than never.

Please [refer to the "Installation" section](https://github.com/media-kit/media-kit#installation).

**Closed by alexmercerind** 2023-07-29 13:27 UTC
Labels: platform: android, re-evaluate in future, in triage
