### ISSUE TITLE
[Enhancement][Native] Smooth seeking/scrubbing

### ISSUE THREAD

**Issue by jtkeyva** [media-kit/media-kit#471] opened 2023-09-11 07:02 UTC
When you slide the seek bar slider, the video doesn't smoothly seek in real-time.  It's choppy and doesn't update the video frame until you lift your finger. 

How can I make a custom scroller/slider that provides smooth video frame changes?

Thanks

**Comment by sbenmeddour** [comment] 2023-09-11 08:06
Make your own `Slider `widget and call `seek()` in `onChanged` callback instead of `onChangeEnd `from slider widget.

**Comment by jtkeyva** [comment] 2023-09-12 04:40
@sbenmeddour thanks, but it's quite choppy. this was an issue with the [video_player package](https://pub.dev/packages/video_player) and this [smooth_video_progress package](https://pub.dev/packages/smooth_video_progress) was a good solution

Here is my code in which the video frames update ok but it's choppy and seems to do it in chunks:

```
import 'package:flutter/material.dart';

// Make sure to add following packages to pubspec.yaml:
// * media_kit
// * media_kit_video
// * media_kit_libs_video
import 'package:media_kit/media_kit.dart'; // Provides [Player], [Media], [Playlist] etc.
import 'package:media_kit_video/media_kit_video.dart'; // Provides [VideoController] & [Video] etc.

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  // Necessary initialization for package:media_kit.
  MediaKit.ensureInitialized();
  runApp(
    const MaterialApp(
      home: MyScreen(),
    ),
  );
}

class MyScreen extends StatefulWidget {
  const MyScreen({Key? key}) : super(key: key);
  @override
  State<MyScreen> createState() => MyScreenState();
}

class MyScreenState extends State<MyScreen> {
  // Create a [Player] to control playback.
  late final player = Player();
  // Create a [VideoController] to handle video output from [Player].
  late final controller = VideoController(player);
  Duration currentPosition = Duration.zero;
  Duration totalDuration = Duration.zero;

  @override
  void initState() {
    super.initState();
    // Play a [Media] or [Playlist].
    player.open(Media(
        'https://user-images.githubusercontent.com/28951144/229373695-22f88f13-d18f-4288-9bf1-c3e078d83722.mp4'));
    controller.player.stream.position.listen((position) {
      setState(() {
        currentPosition = position;
      });
    });

    controller.player.stream.duration.listen((duration) {
      setState(() {
        totalDuration = duration;
      });
    });
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ListView(
          children: [
            SizedBox(
              width: MediaQuery.of(context).size.width,
              height: MediaQuery.of(context).size.width * 9.0 / 16.0,
              // Use [Video] widget to display video output.
              child: Video(
                controller: controller,
                //  controls: videoControls
              ),
            ),
            SliderTheme(
              data: SliderThemeData(
                trackHeight: 3.0,
                thumbShape: RoundSliderThumbShape(enabledThumbRadius: 8.0),
              ),
              child: Slider(
                value: currentPosition.inMilliseconds.toDouble(),
                min: 0,
                max: totalDuration.inMilliseconds.toDouble(),
                onChanged: (double value) {
                  setState(() {
                    currentPosition = Duration(milliseconds: value.toInt());
                    controller.player.seek(currentPosition);
                  });
                },
                onChangeEnd: (double value) {
                  controller.player.seek(currentPosition);
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

Any help greatly appreciated. Thanks

**Comment by sbenmeddour** [comment] 2023-09-12 08:07
I have a better approach but it's not 100% smooth (i think player.seek() is doing work on main thread ? idk)

```dart
import 'package:flutter/material.dart';

// Make sure to add following packages to pubspec.yaml:
// * media_kit
// * media_kit_video
// * media_kit_libs_video
import 'package:media_kit/media_kit.dart'; // Provides [Player], [Media], [Playlist] etc.
import 'package:media_kit_video/media_kit_video.dart'; // Provides [VideoController] & [Video] etc.

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  // Necessary initialization for package:media_kit.
  MediaKit.ensureInitialized();
  runApp(
    const MaterialApp(
      home: MyScreen(),
    ),
  );
}

class MyScreen extends StatefulWidget {
  const MyScreen({Key? key}) : super(key: key);
  @override
  State<MyScreen> createState() => MyScreenState();
}

class MyScreenState extends State<MyScreen> {
  // Create a [Player] to control playback.
  late final player = Player();
  // Create a [VideoController] to handle video output from [Player].
  late final controller = VideoController(player);
  Duration currentPosition = Duration.zero;
  Duration totalDuration = Duration.zero;

  var _isSliderActive = false;
  var _userValue = 0;

  final _throttleHandler = ThrottleHandler<Duration>(delay: const Duration(milliseconds: 50));

  @override
  void initState() {
    super.initState();
    // Play a [Media] or [Playlist].
    player.open(Media('https://user-images.githubusercontent.com/28951144/229373695-22f88f13-d18f-4288-9bf1-c3e078d83722.mp4'));
    controller.player.stream.position.listen((position) {
      setState(() {
        currentPosition = position;
      });
    });
    controller.player.stream.duration.distinct().listen((duration) {
      setState(() {
        totalDuration = duration;
      });
    });
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ListView(
          children: [
            SizedBox(
              width: MediaQuery.of(context).size.width,
              height: MediaQuery.of(context).size.width * 9.0 / 16.0,
              // Use [Video] widget to display video output.
              child: Video(
                controller: controller,
                //  controls: videoControls
              ),
            ),
            SliderTheme(
              data: const SliderThemeData(
                trackHeight: 3.0,
                thumbShape: RoundSliderThumbShape(enabledThumbRadius: 8.0),
              ),
              child: Slider(
                value: _isSliderActive ? _userValue.toDouble() : currentPosition.inMilliseconds.toDouble(),
                min: 0,
                max: totalDuration.inMilliseconds.toDouble(),
                onChanged: (double value) {
                  setState(() {
                    _userValue = value.round();
                  });
                  final target = Duration(milliseconds: value.round());
                  _throttleHandler.run(
                    value: target,
                    action: (it) {
                      player.seek(it);
                    },
                  );
                },
                onChangeEnd: (double value) async {
                  setState(() {
                    _isSliderActive = false;
                  });
                  final target = Duration(milliseconds: value.round());
                  await controller.player.seek(target);
                },
                onChangeStart: (_) {
                  setState(() {
                    _userValue = currentPosition.inMilliseconds;
                    _isSliderActive = true;
                  });
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class ThrottleHandler<T> {

  final Duration delay;

  ThrottleHandler({required this.delay});

  var _lastTime = DateTime.fromMillisecondsSinceEpoch(0, isUtc: true);

  void run({required final T value, required final Function(T value) action}) {
    final now = DateTime.timestamp();
    if (now.difference(_lastTime).abs() < delay) {
      return;
    }
    _lastTime = now;
    action.call(value);
  }

}
```

**Comment by alexmercerind** [comment] 2023-09-12 20:42
> I think `seek` is doing work on main thread?

In `main` branch (next release), `seek` has been moved to another `Isolate`: https://github.com/media-kit/media-kit/commit/d82d0013780a34ff91dd86f866e5f89cede0af07

This eliminates all kind of jank if too many native calls are queued.

@jtkeyva 

However, it's not feasible to eliminate the delay between frame update & seek (even VLC has delay between frame draw & seek). I mean realize yourself work, network, disk, decode, render, I/O etc. can't be synchronous or instant. As you can see on YouTube, that they show a separately fetched thumbnail for that position until seek-bar thumb is held (can be identified by thumbnail's substantially small resolution compared to video). 

As for the jank, referenced commit moves `seek` to another `Isolate` to deal with any performance problems.
As for default seek behavior, it is intentional & preferred to only seek upon mouse is lifted.

If you wish to modify default controls behavior, you can copy-paste code locally & rename (it's literally single file):

[`main`/media_kit_video/lib/media_kit_video_controls/src/controls/material_desktop.dart](https://github.com/media-kit/media-kit/blob/main/media_kit_video/lib/media_kit_video_controls/src/controls/material_desktop.dart)

OR write them from scratch. I'll say if you're building anything serious, you actually should (to add identity to your project).

**Comment by jtkeyva** [comment] 2023-09-13 04:36
@alexmercerind thanks, i look forward to the new release!

one trick i figured out was to simply speed up the video for fast forward seek. but there is not -.4 speed.

can there be a negative speed option to play back the video in reverse? that would be amazing!

for short form videos in which the entire video has already been downloaded it should be very smooth back and forth with no delay. just as it is with the video_player and smooth_video_progress package. give it a try if you can. the experience is beautiful.

**Comment by jtkeyva** [comment] 2023-09-13 05:40
@sbenmeddour interesting solution, that works ok. but if you swipe the slider, it does so in "chunks". which is a the main problem i'm trying to solve. it's not a silky smooth swipe.

i was trying to start simple with a slider but what i'm really going for is a listview to be able to control the seeking similar to a non-linear video editor. so perhaps a listview that has timecode numbers ex 1s, 2s, 3s etc. that scrolls as the video plays.

and you can swipe the list view to 21s and it smoothly seeks through to the 21second point in the video. and same with reverse.

i have sucessfully done this with video_player and smooth_video_progress package and perhaps i just need to stop spending so much time trying to "port" it to media_kit. but this seems like a very promising package.

any help apprediate. thx

**Comment by jtkeyva** [comment] 2023-09-13 05:59
You can see my video_player version in action here:

https://i.imgur.com/DjOHDcs.mp4

Notice how smooth (except gif is only 12fps) and responsive it is

**Comment by jtkeyva** [comment] 2023-09-16 19:44
Anyone have any more suggestions or ideas?

**Comment by sbenmeddour** [comment] 2023-09-16 20:36
> In `main` branch (next release), `seek` has been moved to another `Isolate`: [d82d001](https://github.com/media-kit/media-kit/commit/d82d0013780a34ff91dd86f866e5f89cede0af07)
> 
> This eliminates all kind of jank if too many native calls are queued.

Wait for next release, or use main branch and git repo as media_kit depencency

**Comment by jtkeyva** [comment] 2023-09-17 08:13
tried lots of combiniations but none work. your repo is different than most packages and not sure how to depend on it. please help

```
  media_kit:
    git:
      # url: https://github.com/media-kit/media-kit
      url: https://github.com/media-kit/media-kit/media_kit
      # url: https://github.com/media-kit/media-kit/tree/main/media_kit
      ref: main
  media_kit_video: ^1.1.8 # For video rendering.
  media_kit_libs_video: ^1.0.1  # Native video dependencies.
```

**Comment by birros** [comment] 2023-09-17 08:30
> tried lots of combiniations but none work. your repo is different than most packages and not sure how to depend on it. please help

```yaml
dependencies:
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./libs/universal/media_kit_libs_video

dependency_overrides:
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./libs/universal/media_kit_libs_video
```

**Comment by jtkeyva** [comment] 2023-09-17 19:40
wow thanks, that's quite extensive. i am trapped in this now:

```
Resolving dependencies...
The current Dart SDK version is 3.1.0.

Because video_sandbox depends on dependencies any which doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=2.0.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety
exit code 1```

still getting errors even though i have it set to:
environment:
  sdk: '>=2.18.0 <3.0.0'

**Comment by jtkeyva** [comment] 2023-09-30 06:02
@alexmercerind i've got the new release and i'm still getting choppy seeking. is this fixable?

**Comment by sbenmeddour** [comment] 2023-10-04 22:28
Maybe if you remove the suffix "absolute" in the mpv seek command it may be faster

**Comment by jtkeyva** [comment] 2023-10-21 20:21
@sbenmeddour thanks, but not sure what you mean? i still can't get this to work silky smooth like video_player scrubbing

**Comment by jtkeyva** [comment] 2023-10-21 20:25
> > I think `seek` is doing work on main thread?
> 
> In `main` branch (next release), `seek` has been moved to another `Isolate`: [d82d001](https://github.com/media-kit/media-kit/commit/d82d0013780a34ff91dd86f866e5f89cede0af07)
> 
> This eliminates all kind of jank if too many native calls are queued.
> 
> @jtkeyva
> 
> However, it's not feasible to eliminate the delay between frame update & seek (even VLC has delay between frame draw & seek). I mean realize yourself work, network, disk, decode, render, I/O etc. can't be synchronous or instant. As you can see on YouTube, that they show a separately fetched thumbnail for that position until seek-bar thumb is held (can be identified by thumbnail's substantially small resolution compared to video).
> 
> As for the jank, referenced commit moves `seek` to another `Isolate` to deal with any performance problems. As for default seek behavior, it is intentional & preferred to only seek upon mouse is lifted.
> 
> If you wish to modify default controls behavior, you can copy-paste code locally & rename (it's literally single file):
> 
> [`main`/media_kit_video/lib/media_kit_video_controls/src/controls/material_desktop.dart](https://github.com/media-kit/media-kit/blob/main/media_kit_video/lib/media_kit_video_controls/src/controls/material_desktop.dart)
> 
> OR write them from scratch. I'll say if you're building anything serious, you actually should (to add identity to your project).

@alexmercerind i understand there is a delay/latencty that you cannot seem to fix. however using video_player it is instantaneous and silky smooth. is there no way to get it working like so?

**Comment by alexmercerind** [comment] 2023-10-21 20:27
I have to explore few things before I can say. There should be some solution.

However, yeah the seeking is moved to another `Isolate` now.

**Comment by alexmercerind** [comment] 2023-10-21 20:29
Re-opening the thread; so that it stays on top of my head.

**Comment by alexmercerind** [comment] 2023-10-21 21:10
@jtkeyva 

Do you mind sharing minimal sample (like the one in the video you shared above) w/ package:video_player?

**Comment by jtkeyva** [comment] 2023-10-23 06:13
@alexmercerind

i can share this tidbit. please let me know if it helps or if you need some more details. i really want to use media kit but this is an essential functionality to glide through video frames. and i think you might want to look at this package

https://pub.dev/packages/smooth_video_progress

`
void _syncTimelineWithVideoPosition() {
    if (_videoController.value.isInitialized &&
        !_timelineScrollController.position.isScrollingNotifier.value) {
      final offset = _videoController.value.position.inMilliseconds /
          _videoController.value.duration.inMilliseconds *
          _timelineScrollController.position.maxScrollExtent;
      _timelineScrollController.jumpTo(offset);
    }
  }

  void _syncVideoPositionWithTimeline() {
    if (_videoController.value.isInitialized) {
      final position = Duration(
          milliseconds: (_timelineScrollController.offset /
                  _timelineScrollController.position.maxScrollExtent *
                  _videoController.value.duration.inMilliseconds)
              .round());
      _videoController.seekTo(position);
    }
  }`

**Comment by cbenhagen** [comment] 2023-11-23 11:30
@alexmercerind This even more noticeable when using the example in `video_player_media_kit`. The seek bar is unusable there as it will seek on every update of the scrollbar and the seek requests quickly pile up. Maybe new seek requests could cancel old ones until seeking can be made smoother?

What can be done to make it as smooth as the now officially available `video_player_avfoundation` implementation (which has other issues unfortunately)?

**Comment by kaciula** [comment] 2024-01-22 11:13
I also need to be able to seek frame by frame as much as possible. My current solution is using throttling of seek calls (similar to wha was posted previously here) but it's not great.

Maybe the plugin can expose a method to cancel an in-progress seek call? This way, when dragging we can cancel previous seek call instead of doing a 100 ms debounce delay.

**Comment by cbenhagen** [comment] 2024-01-22 11:51
@kaciula I think the plugin should handle this on its own instead of exposing this. If it could cancel old requests that would already be a lot better already. But still far from the smooth scrolling our users would expect to see.

@alexmercerind what are your thoughts on this? Is this a limitation of `libmpv`?

**Comment by lei-cao** [comment] 2024-02-13 09:37
I am facing the same problem. 
My first version was using https://github.com/zezo357/flutter_meedu_videoplayer , I didn't have the laggy issue, since it's discontinued, I switched to media-kit, I like the rest of the features of media-kit, but the seek laggy is annoying. 
I tried to use https://github.com/media-kit/media-kit/commit/d82d0013780a34ff91dd86f866e5f89cede0af07 this commit too, didn't see improvement neither.

I tested video_player with almost the same code logic, the seek, skip was very fast and smooth, it should be media_kits problem. But the problem for video_player is it's controller, every time change video, it has to create a new controller, I tried to quickly switch to different video (local files) which is required by my app, it stuck soon, likely memory leaked.. Well, with the same code, media_kit doesn't have this problem. video_player seems need to manage dispose better manually, need to do more refactoring of my code if I switch to video_player. But since quick and smooth skip/seek is very crucial to my app, I still have to try to have a  video_player version of that feature.

In general, media_kit is still much easier to use if the laggy got fixed. Hope it got fixed.

**Comment by zezo357** [comment] 2024-02-13 09:49
> I am facing the same problem. My first version was using https://github.com/zezo357/flutter_meedu_videoplayer , I didn't have the laggy issue, since it's discontinued, I switched to media-kit, I like the rest of the features of media-kit, but the seek laggy is annoying. I tried to use [d82d001](https://github.com/media-kit/media-kit/commit/d82d0013780a34ff91dd86f866e5f89cede0af07) this commit too, didn't see improvement neither.
> 
> I tested video_player with almost the same code logic, the seek, skip was very fast and smooth, it should be media_kits problem. But the problem for video_player is it's controller, every time change video, it has to create a new controller, I tried to quickly switch to different video (local files) which is required by my app, it stuck soon, likely memory leaked.. Well, with the same code, media_kit doesn't have this problem. video_player seems need to manage dispose better manually, need to do more refactoring of my code if I switch to video_player. But since quick and smooth skip/seek is very crucial to my app, I still have to try to have a video_player version of that feature.
> 
> In general, media_kit is still much easier to use if the laggy got fixed. Hope it got fixed.

i think the reason for the fast seek is using exoplayer, https://github.com/media-kit/media-kit/issues/410 if that issue got resolved on android the fast seek will be possible, but for mpv i dont have the knowledge sadly to know why its not fast enough

**Comment by kaciula** [comment] 2024-03-20 07:59
Here is some more feedback in case it helps.

I'm using ffmpeg to get the timestamps for all the video frames so that the user can seek a video frame by frame. What I noticed is that when seeking the next/previous frame, the current playback position stream always returns 2 consecutive events, even though I seeked the very next/previous frame. Not sure what the intermediary position represents (it always has zeroes for the last 3 microsecond digits ) but there is no actual frame at that position. Maybe the code can be optimized to not go through these intermediary non-frame positions and thus potentially half the time it takes to do the seeking in general. 

```
User seeks to next frame at 299989 microseconds
Stream position updated to 0:00:00.299000
Stream position updated to 0:00:00.299988
User seeks to next frame at 366611
Stream position updated to 0:00:00.366000
Stream position updated to 0:00:00.366611
```

**Comment by default-anton** [comment] 2024-04-29 06:15
After spending about 16 hours debugging why seek is so slow on my Apple M1 Pro, I finally figured it out.
It turns out, there is an issue with hardware decoding on M1/M2 macs.

I open a video with `mpv`, it's fast. I open the same video with IINA or media-kit, the seek is slow.

By default, `mpv` has `hwdec=no`, and sure thing, when I disable `hwdec` in media-kit, seek becomes instantaneous. 
```dart
VideoController controller = VideoController(
  player,
  configuration: const VideoControllerConfiguration(
    hwdec: 'no',
  ),
);
```

There is a similar thread about this issue in IINA https://github.com/iina/iina/issues/4243

I have an idea I want to try later this week. `libmpv` allows changing `hwdec` at any moment. If the platform is darwin and arch is arm64, then seek becomes:
1. hwdec=no
2. seek
3. hwdec=auto

If that doesn't work out, we should at least document this behavior.

FYI @alexmercerind @abdelaziz-mahdy

**Comment by alexmercerind** [comment] 2024-04-29 08:35
Disabling hardware acceleration is not a solution. It's available as an option for extreme use-cases e.g. broken files or obscure video formats.

> If that doesn't work out, we should at least document this behavior.

I don't think this is a bug or unintended behavior. It would've been a deal breaker e.g. if the seek didn't work at all.

This is just slight difference in how things work. Every software has pros/cons. The thread is left open in case one finds any actual solutions, the `setProperty` & `command` API is available publicly for everyone to experiment. I personally have spent too much time on this back in the day, with only little improvements.

> There is a similar thread about this issue in IINA https://github.com/iina/iina/issues/4243

https://github.com/iina/iina/issues/3735 is the thread which you should be actually looking at.

**Comment by default-anton** [comment] 2024-04-29 16:10
I tried the config from https://github.com/iina/iina/issues/3735, but didn't see any improvement when seeking large h.264 files. However, setting `hwdec=no` makes seeking incredibly fast. 

I'll soon be working with various video encoders and formats on macOS. Would we be interested in optimizing the playback experience on macOS? I'll be doing it anyway, so I might as well contribute back any optimizations I find.

I realize I might end up fine-tuning `mpvlib` for every single combination of format/encoder on Macs, and that's okay. As long as customers are happy, I'm good with that!

**Comment by abdelaziz-mahdy** [comment] 2024-04-29 16:48
> I tried the config from https://github.com/iina/iina/issues/3735, but didn't see any improvement when seeking large h.264 files. However, setting `hwdec=no` makes seeking incredibly fast. 
> 
> I'll soon be working with various video encoders and formats on macOS. Would we be interested in optimizing the playback experience on macOS? I'll be doing it anyway, so I might as well contribute back any optimizations I find.
> 
> I realize I might end up fine-tuning `mpvlib` for every single combination of format/encoder on Macs, and that's okay. As long as customers are happy, I'm good with that!

I would love to see the configuration you land on using, since i am using macos too and seek is Abit slow, for Android the seek is good for me

**Comment by jtkeyva** [comment] 2024-08-24 18:32
still dreaming of a smooth seek/scrub. any ideas if/when it can be implemented?

**Comment by abdelaziz-mahdy** [comment] 2024-08-24 18:54
> still dreaming of a smooth seek/scrub. any ideas if/when it can be implemented?

I am personally using fvp, the seek is much better there but of course you will make changes to code and I don't use subtitles from player nor playlist

**Comment by jtkeyva** [comment] 2024-08-24 21:35
@abdelaziz-mahdy thanks for the info, just tried that for the first time. wasn't able to get the example working on ios. for web it seems nice.

but i didn't see a way to scrub the timeline? i can only click on it and it instantly jumps to that frame which is great... but i want to be able to scrub through the frames frame by frame. right now it jumps around.

can you tell me how you got smooth seeking/scrubbing?

i like the idea of looping certain sections of the video. have you made any customizations?

**Comment by abdelaziz-mahdy** [comment] 2024-08-24 22:01
> @abdelaziz-mahdy thanks for the info, just tried that for the first time. wasn't able to get the example working on ios. for web it seems nice.
> 
> but i didn't see a way to scrub the timeline? i can only click on it and it instantly jumps to that frame which is great... but i want to be able to scrub through the frames frame by frame. right now it jumps around.
> 
> can you tell me how you got smooth seeking/scrubbing?
> 
> i like the idea of looping certain sections of the video. have you made any customizations?

I don't personally use smooth scrubbing but due to the player seeking not taking much time scrubbing should work correctly I think

**Comment by jtkeyva** [comment] 2024-08-25 05:01
ok thanks, i'll look into it

**Comment by nateshmbhat** [comment] 2024-09-06 15:10
when is the next release happening ? in github releases, i'm not seeing latest releases that were released on pub.dev

**Comment by BinaryQuantumSoul** [comment] 2024-09-15 19:32
Everything works fine except this. I think I will have to use another library just for playing the audio because i had absolutely no position jumps with audio_player lib but here the seeking is completely cursed

**Comment by alexmercerind** [comment] 2024-09-26 21:11
Hey guys!

I understand there has been a lot of delay... I have been busy with life. With that being said, I finally found a fix for this issue.

Expect seeking too be very smooth from the next release of package:media_kit.

https://github.com/user-attachments/assets/57d02718-7ad4-48d8-8e55-ea245e1dd13e

**Comment by jtkeyva** [comment] 2024-09-26 21:23
looking forward to it! thx

**Comment by BinaryQuantumSoul** [comment] 2024-09-26 22:18
am hyped

**Comment by Ansh-Rathod** [comment] 2024-09-27 14:52
LETS GO!

**Comment by alexmercerind** [comment] 2024-09-28 18:30
Build against main branch.

**Closed by alexmercerind** 2024-09-28 18:30 UTC
Labels: enhancement, backend: native

**Comment by jtkeyva** [comment] 2024-09-29 18:43
@alexmercerind thanks just tested.

it's smooth scrubbing for the first 1/10 of the video but then becomes choppy again. only tested on chrome so far

**Comment by alexmercerind** [comment] 2024-09-29 18:52
@jtkeyva

This issue was only relevant for `NativePlayer` (backed by libmpv) i.e. Android, iOS, macOS, GNU/Linux & Windows.

I haven't modified anything for the `WebPlayer`. I can't change how the web browser operates. With that being said, if you are playing some network resource, things like caching, buffering & network connection etc. will still play their role.

<hr>

The seeking/scrubbing on macOS is same as that on QuickTime now. You can download our test application from the CI (scroll down for artifacts) for evaluation purposes:

https://github.com/media-kit/media-kit/actions/runs/11092566763

**Comment by jtkeyva** [comment] 2024-09-29 20:50
ah ok will try it thanks
@alexmercerind the example does not work on macos

Command PhaseScriptExecution failed with a nonzero exit code
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **

**Comment by alexmercerind** [comment] 2024-09-29 20:54
Our CI succeeds.
