### ISSUE TITLE
[Bug Report][Windows][Regression] M3U8 playback breaking change with 'media_kit_libs_windows_video' 1.0.4

### ISSUE THREAD

**Issue by Vocatis** [media-kit/media-kit#307] opened 2023-07-25 14:33 UTC
Hi,

it's awsome work your doing here, I discovered this project a few days ago before the v1.1.0 release, and been testing it on Windows and Android.

So I ran into a problem with the 1.0.4 version of '_media_kit_libs_windows_video_'.
M3U8 file reading no longer works as it should.
Playback seems to be segment by segment, rather than for the whole file, and track detection/selection is no longer available.

To be more explicit, here's an example, and this way you'll be able to reproduce it too.
Using this file: [Test file](https://media.axprod.net/TestVectors/Hls/not_protected_hls_1080p_h264/manifest.m3u8)
It contains 6 video tracks, 3 audio tracks and 3 subtitle tracks for a duration of 12 minutes.

With version 1.0.2:
- I can see that the video is 12 minutes long, seek in the video as long as it has loaded but not afterwards or it won't load again.
- Playback is smooth.

With version 1.0.4:
- I can't see the total duration, so I can't seek in the video.
- Playback is segmented and jerky.
- I can't see the other tracks.

NB: 
I retrieve information on the availability of video, audio and subtitle tracks with:

- `player.state.tracks.video;`
- `player.state.tracks.audio;`
- `player.state.tracks.subtitle;`

384x216 video track is not available (with Android too).
Subtitles are not detected in both versions (with Android too).

**Comment by Vocatis** [comment] 2023-07-25 17:02
> I hope the package is meeting your demand.

@alexmercerind Yes it's very promising, I'm still testing to see if I can easily fit all my "needs".
I might have some questions coming. I'll use your Discord server for that it's more suitable I think.
I will gladly assist with my feedback.

> Please pin your media_kit_libs_windows_video version till then, I'll try to fix this shortly (may take a few hours).

Yes that's what I did for now '_media_kit_libs_windows_video_' 1.0.2 works fine with '_media_kit_'  & '_media_kit_video_' 1.1.0
Thanks for the quick reply, no problem, take the time you need, there's no hurry on my side.

**Comment by postacik** [comment] 2023-07-25 17:55
I pinned media_kit_libs_windows_video to 1.0.2 with the following line: (I suppose that's what you mean)

```yaml
media_kit_libs_windows_video: 1.0.2
```

then after...

```
flutter clean
flutter pub get 
flutter run
```

...the url opened without any issues...

**Comment by alexmercerind** [comment] 2023-07-25 17:56
> I pinned media_kit_libs_windows_video to 1.0.2 with the following line: (I suppose that's what you mean)
> 
> ```yaml
> media_kit_libs_windows_video: 1.0.2
> ```
> 
> then after...
> 
> ```
> flutter clean
> flutter pub get 
> flutter run
> ```
> 
> ...the url opened without any issues...

No I totally didn't mean that to you. It's not a solution.

**Comment by alexmercerind** [comment] 2023-07-29 13:23
The issue is resolved in the latest update.

Please [refer to the "Installation" section](https://github.com/media-kit/media-kit#installation).

**Comment by alexmercerind** [comment] 2023-07-29 13:24
HLS now works correctly on Windows.
DASH now works correctly on Android.
WebVTT subtitles now load over HLS.

**Closed by alexmercerind** 2023-07-29 13:23 UTC
Labels: bug, platform: windows, platform: android

**Comment by MJ33** [comment] 2023-08-11 12:12
Hi @alexmercerind, I would also like to thank you for an awesome package.

Unfortunately, I am also having the same issue as @Vocatis.

I am using the following versions in my Flutter Windows app:

> media_kit: ^1.1.3
> media_kit_libs_windows_video: ^1.0.6
> media_kit_video: ^1.1.3

The example I'm using has 3 segments of .ts files (~10sec each) which should show a duration of ~30sec, but the video is showing a 9sec duration, then moving to the next segment, etc.

On VLC the stream shows 29sec duration.

Could there be something wrong with the .m3u8 file?

> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-TARGETDURATION:10
> #EXT-X-MEDIA-SEQUENCE:0
> #EXT-X-DISCONTINUITY
> #EXTINF:9.955000,
> #EXT-X-PROGRAM-DATE-TIME:2023-08-10T15:37:51.678+0200
> Test000000505.ts
> #EXTINF:9.970000,
> #EXT-X-PROGRAM-DATE-TIME:2023-08-10T15:38:01.633+0200
> Test000000506.ts
> #EXTINF:9.995000,
> #EXT-X-PROGRAM-DATE-TIME:2023-08-10T15:38:11.603+0200
> Test000000507.ts
> #EXT-X-ENDLIST

**Comment by alexmercerind** [comment] 2023-08-11 12:16
Can you share sample here or on my email <alexmercerind@gmail.com>?

**Comment by MJ33** [comment] 2023-08-11 12:32
I'll set up a sample for you and send it in a moment, thank you
