### ISSUE TITLE
`Player.seek` updates state with delay.

### ISSUE THREAD

**Issue by krida2000** [media-kit/media-kit#396] opened 2023-08-22 11:27 UTC
``` dart 

print('widget.controller.player.position: ${widget.controller.player.state.position}');
await widget.controller.player.seek(Duration(minutes: 1));
print('widget.controller.player.position: ${widget.controller.player.state.position}');

```

Second `print` prints the same time as first, even if `Player.seek` awaited. I think `state` must be already updated after `await Player.seek`.

**Comment by alexmercerind** [comment] 2023-08-22 11:30
It's working as intended, most multimedia operations are asynchronous. You shouldn't rely on this behavior.

**Comment by krida2000** [comment] 2023-08-22 11:40
And we can't await this asynchronous operation? Why is `Player.seek` returns `Future` if we can't await for it? Looks strange.

**Comment by alexmercerind** [comment] 2023-08-22 11:45
And what if a network request fails upon seek, wouldn't `Player.seek` deadlock?

I'm genuinely unable to understand your use-case, if your `Player.seek` request is successful, the `position.stream.position`/`player.state.position` will update. The stream based async event updates are provided for the same reason.

If you have a convincing use-case, I'll take a look, other than that we haven't received any complaints. Most of the times, the problems may be resolved by writing code in a different & more effective manner.

**Comment by krida2000** [comment] 2023-08-22 11:57
Found a same issue, with what I faced, in your example in web. Progress bar is jumping after rewinding.


https://github.com/media-kit/media-kit/assets/71345244/06a069bf-6bf8-49c5-8164-ea59a6bb575b

**Comment by alexmercerind** [comment] 2023-08-22 20:19
It actually makes the point more obvious that it's not necessary that calling seek will actually update the position (how Chrom(e|ium)'s own implementation behaves). It takes time to fetch stream, decode & play.

The issue isn't in the `Player` implementation, but rather just a small UX issue within controls, which has been resolved:

https://github.com/media-kit/media-kit/commit/d2cd3c869427b9d5d24412f596a92b9a2d825b71

Trust me it's more sensible to not update the position immediately within `Player.seek` or wait for it to happen. The event states/streams are provided for the same reasons, to handle the asynchronous nature of events & operations which occur during the playback.

Thanks!

**Closed by alexmercerind** 2023-08-22 20:19 UTC
Labels: in triage

**Comment by alexmercerind** [comment] 2023-08-25 20:22
A new version has been published (refer to "Installation" section of the README).

In our [web demo](https://media-kit.github.io/media-kit/#/), seek-bar does not glitch anymore.

Thanks!

**Comment by Zensonaton** [comment] 2025-02-19 09:29
For future researchers: you can do something wacky like this:
```dart
print("Before: ${player.state.position}");
await player.seek(position);
await for (final _ in player.stream.position.take(1)) {} // <-
print("After: ${player.state.position}");
```

If you are creating a wrapper for `media_kit`'s Player, then you can do something like...
```dart
class MyPlayer {
  final Player player = ...;

  Duration? _tempPosition;
  Duration get position => _tempPosition ?? player.state.position;

  Future<void> seek(Duration position) {
    _tempPosition = position;
    await player.seek(position);
    await for (final _ in player.stream.position.take(1)) {}
    _tempPosition = null;
  }
}
```
