### ISSUE TITLE
Application Error in Release Mode on Windows

### ISSUE THREAD

**Issue by azulmouad** [media-kit/media-kit#861] opened 2024-06-10 20:45 UTC
The application runs successfully in debug mode on Windows, but encounters an error when running in release mode.

**Error Message**
When running the application in release mode, the following error message is displayed:

```
package:media_kit_libs_windows_video registered.
Problem getting monitor brightness
```

**Comment by haorendashu** [comment] 2024-06-17 07:40
After upgrade to the flutter 3.22.2, I get the same issue.

And my application can't run success.

**Comment by atulkumar6556** [comment] 2024-06-22 05:59
@azulmouad @haorendashu   ---   Is your issue resolved ?

**Comment by azulmouad** [comment] 2024-06-22 07:06
> @azulmouad @haorendashu   ---   Is your issue resolved ?

No, still facing same issues

**Comment by haorendashu** [comment] 2024-06-23 02:34
@atulkumar6556 @azulmouad Go to you pre release version, copy these three file to replace the new files:

```
media_kit_libs_windows_video_plugin.dll
media_kit_native_event_loop.dll
media_kit_video_plugin.dll
```

Maybe your project don't have these three files.

**Comment by azulmouad** [comment] 2024-06-23 04:46
> @atulkumar6556 @azulmouad Go to you pre release version, copy these three file to replace the new files:
> 
> ```
> media_kit_libs_windows_video_plugin.dll
> media_kit_native_event_loop.dll
> media_kit_video_plugin.dll
> ```
> 
> Maybe your project don't have these three files.

Works , Thanks

**Comment by haorendashu** [comment] 2024-06-23 05:12
This issue shouldn't be closed.

It remain need to be handled.

**Comment by azulmouad** [comment] 2024-06-24 04:37
Yeah this issues still appears

**Comment by CaptainDario** [comment] 2024-06-28 04:50
@alexmercerind, this is still happening for me, too. Because of this I my app is in a broken state.

**Comment by alexmercerind** [comment] 2024-06-28 18:55
We need to delete following files in final directory:

```
api-ms-*.dll
concrt140.dll
msvcp*.dll
ucrtbas*.dll
vc*.dll
```

It is due to breaking change in MSVCP or UCRT from Microsoft. These DLLs are coming from ANGLE:
https://github.com/media-kit/media-kit/blob/ff00dae2b9bb6e66cdf15a7ecc1f99d0b7d6e3b4/libs/windows/media_kit_libs_windows_video/windows/CMakeLists.txt#L103


The message "Problem getting monitor brightness" is not an error itself... it is coming from [package:screen_brightness](https://pub.dev/packages/screen_brightness).

**Comment by salim-maula** [comment] 2024-06-29 19:57
thks info, but my video still loading. canot playing if i delete 

api-ms-*.dll
concrt140.dll
msvcp*.dll
ucrtbas*.dll
vc*.dll

how to solve it

this is my code to play video
`import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';
import 'package:vending_machine/view/home/home.dart';


class OnboardingPage extends StatefulWidget {
  const OnboardingPage({super.key});

  @override
  _OnboardingPageState createState() => _OnboardingPageState();
}

class _OnboardingPageState extends State<OnboardingPage> {
  late Player _player;
  late VideoController _videoController;

  @override
  void initState() {
    super.initState();
    _initializePlayer();
  }

  void _initializePlayer() async {
    _player = Player();
    _videoController = VideoController(_player);
    await _player.open(Media('assets/videos/video.mp4')); // Ganti dengan link video yang valid
    _player.play();
    _player.setPlaylistMode(PlaylistMode.loop);
  }

  @override
  void dispose() {
    _player.dispose();
    super.dispose();
  }

  void _onTap() {
    _player.pause();
    Navigator.of(context).pushReplacement(
      MaterialPageRoute(builder: (_) => const Home()), // Ganti dengan halaman tujuan
    );
  }

  @override
  Widget build(BuildContext context) {
    return 
    Scaffold(
      body: Stack(
        children: [
          Video(
            controller: _videoController),
          Center(
            child: GestureDetector(
              onTap: _onTap,
              child: Container(
                color: Colors.transparent,
                width: double.infinity,
                height: double.infinity,
                padding: const EdgeInsets.all(20),
                child: const Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(Icons.touch_app,size: 50,color: Colors.white,),
                    Text(
                      'Sentuh Untuk Melanjutkan',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 50,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

`
<img width="959" alt="Screenshot 2024-06-30 025658" src="https://github.com/media-kit/media-kit/assets/70277145/909afa51-9210-4dd7-ac95-2830b3d3f4f2">

**Comment by alexmercerind** [comment] 2024-06-30 06:06
@salim-maula use `asset://` prefix to load assets.

**Comment by Clushdada** [comment] 2024-07-02 15:39
> 我们需要删除最终目录中的以下文件：
> 
> ```
> api-ms-*.dll
> concrt140.dll
> msvcp*.dll
> ucrtbas*.dll
> vc*.dll
> ```
> 
> 这是由于 Microsoft 的 MSVCP 或 UCRT ABI 中的重大更改。这些 DLL 来自 ANGLE：
> 
> https://github.com/media-kit/media-kit/blob/ff00dae2b9bb6e66cdf15a7ecc1f99d0b7d6e3b4/libs/windows/media_kit_libs_windows_video/windows/CMakeLists.txt#L103
> 
> 消息“显示器亮度问题”本身不是错误...它来自 [package：screen_brightness](https://pub.dev/packages/screen_brightness)。

我在win10上面用这个办法可以，在win11上面就没用，还有什么更好的办法？或者还有啥好的播放器可以用？

**Comment by atulkumar6556** [comment] 2024-07-10 11:27
[ RESOLVED ]

Duplicate of #862 

[https://github.com/media-kit/media-kit/issues/862#issuecomment-2220258185](url)

**Comment by alexmercerind** [comment] 2024-09-28 16:34
Build against main branch.

**Closed by alexmercerind** 2024-09-28 16:34 UTC
